/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type AnswerMappingThreshold = number;
export type ChallengesUsed = number;
export type MaxChallenges = number;
export type MaxProposalAttempts = number;
export type MinEigToAsk = number;
export type TurnBudget = number;
export type TurnsUsed = number;
export type Assumptions = string[];
export type Differentiator = string;
export type EvidenceIds = string[];
export type FailureModes = string[];
export type Id = string;
export type Mechanism = string;
export type Status = "generated" | "kept" | "combined" | "rejected";
export type Text = string;
export type UserNote = string;
export type Verification = string;
export type CandidateId = string | null;
export type ClaimId = string | null;
export type ConfirmedByTurnId = string | null;
export type Id1 = string;
export type Source = "model_generated_probe" | "user_provided";
export type Status1 = "untested" | "holds" | "does_not_hold" | "conditional" | "not_encountered" | "unknown";
export type Text1 = string;
export type ConfirmedByTurnId1 = string | null;
export type Status2 = "untested" | "user_supported" | "user_rejected" | "conditional";
export type Text2 = string;
export type Boundaries = Boundary[];
export type Confidence = number;
export type AssertedBy = "user" | "model" | "source";
export type EvidenceId = string;
export type Quote = string;
export type Relation = "supports" | "refutes" | "qualifies";
export type TurnId = string | null;
export type EvidenceLinks = EvidenceLink[];
export type Id2 = string;
export type SourceTier = "primary" | "secondary" | "model_only";
export type Status3 = "model_proposal" | "user_confirmed" | "rejected";
export type Text3 = string;
export type Type = "fact" | "heuristic" | "inference" | "goal" | "model_proposal";
export type AnswerOptionId = string | null;
export type EntropyAfter = number | null;
export type EntropyBefore = number;
export type HypothesisSetId = string;
export type HypothesisSetVersion = number;
export type PredictedEig = number;
export type QuestionId = string;
export type EventId = string;
export type RunId = string;
export type SchemaVersion = string;
export type Sequence = number;
export type SessionId = string;
export type Timestamp = string;
export type Type1 =
  | "run.started"
  | "phase.changed"
  | "message.delta"
  | "message.completed"
  | "source.added"
  | "candidate.created"
  | "candidate.updated"
  | "challenge.created"
  | "claim.updated"
  | "learning_check.created"
  | "interrupt.requested"
  | "interrupt.resolved"
  | "run.completed"
  | "run.failed"
  | "run.cancelled";
export type Context = string;
export type CurrentInterpretation = string[];
export type Id3 = string;
export type Kind =
  | "personal_event"
  | "experiment_observation"
  | "paper_passage"
  | "course_example"
  | "code_result"
  | "advisor_feedback"
  | "official_documentation"
  | "source_code"
  | "research_paper"
  | "runtime_observation"
  | "model_knowledge";
export type LaterLearned = string[];
export type Locator = string;
export type ObservedAtTime = string[];
export type Quote1 = string;
export type Relation1 = "supports" | "refutes" | "qualifies";
export type TurnId1 = string | null;
export type SourceSpans = SourceSpan[];
export type SourceTier1 = "primary" | "secondary" | "model_only";
export type Status4 = "model_proposal" | "user_confirmed" | "retrieved";
export type Title = string;
export type Version = string | null;
export type Id4 = string;
export type P = number;
export type Text4 = string;
export type Hypotheses = Hypothesis[];
export type Id5 = string;
export type LatentVariable = string;
export type Status5 = "draft" | "frozen" | "closed";
export type Version1 = number;
export type FreeTextAllowed = boolean;
export type Kind1 = "question" | "learning_check";
export type LearningCheckId = string | null;
export type Id6 = string;
export type Label = string;
export type Options = QuestionOption[];
export type QuestionId1 = string | null;
export type Text5 = string;
export type ExpectedSignals = string[];
export type Feedback = string;
export type Id7 = string;
export type Kind2 = "explain" | "predict" | "exercise" | "implement";
export type Prompt = string;
export type Status6 = "pending" | "answered" | "skipped";
export type UserAnswer = string;
export type Content = string;
export type CreatedAt = string;
export type Id8 = string;
export type Role = "user" | "assistant" | "system";
export type HypothesisSetId1 = string | null;
export type Id9 = string;
export type Kind3 = "discrete" | "open";
export type Options1 = QuestionOption[];
export type Text6 = string;
export type Depth = "fast" | "deep";
export type DesiredOutput = string;
export type MissingInformation = string[];
export type NeedFreshSources = boolean;
export type TaskType = "learn" | "solve" | "compare" | "design" | "research" | "brainstorm" | "externalize";
export type Topic = string;
export type Name = "relevance" | "specificity" | "evidence" | "novelty" | "actionability" | "robustness";
export type Weight = number;
export type ValueCriteria = ValueCriterion[];

/**
 * 知识激发智能体前后端共享事件协议（schema_version 1）。由 scripts/gen_schema.py 生成，请勿手工编辑。
 */
export interface KelEventProtocol {
  budget: Budget;
  candidate: Candidate;
  challenge: Challenge;
  claim: Claim;
  entropy_record: EntropyRecord;
  event: Event;
  evidence_item: EvidenceItem;
  hypothesis_set: HypothesisSet;
  interrupt_payload: InterruptPayload;
  learning_check: LearningCheck;
  message: Message;
  question: Question;
  task_frame: TaskFrame;
  value_criterion: ValueCriterion;
}
export interface Budget {
  answer_mapping_threshold?: AnswerMappingThreshold;
  challenges_used?: ChallengesUsed;
  max_challenges?: MaxChallenges;
  max_proposal_attempts?: MaxProposalAttempts;
  min_eig_to_ask?: MinEigToAsk;
  turn_budget?: TurnBudget;
  turns_used?: TurnsUsed;
}
export interface Candidate {
  assumptions?: Assumptions;
  differentiator?: Differentiator;
  evidence_ids?: EvidenceIds;
  failure_modes?: FailureModes;
  id: Id;
  mechanism?: Mechanism;
  scores?: Scores;
  status?: Status;
  text: Text;
  user_note?: UserNote;
  verification?: Verification;
}
export interface Scores {
  [k: string]: number;
}
export interface Challenge {
  candidate_id?: CandidateId;
  claim_id?: ClaimId;
  confirmed_by_turn_id?: ConfirmedByTurnId;
  id: Id1;
  source?: Source;
  status?: Status1;
  text: Text1;
}
export interface Claim {
  boundaries?: Boundaries;
  confidence?: Confidence;
  evidence_links?: EvidenceLinks;
  id: Id2;
  source_tier?: SourceTier;
  status?: Status3;
  text: Text3;
  type?: Type;
}
export interface Boundary {
  confirmed_by_turn_id?: ConfirmedByTurnId1;
  status?: Status2;
  text: Text2;
}
export interface EvidenceLink {
  asserted_by?: AssertedBy;
  evidence_id: EvidenceId;
  quote?: Quote;
  relation?: Relation;
  turn_id?: TurnId;
}
export interface EntropyRecord {
  answer_option_id?: AnswerOptionId;
  entropy_after?: EntropyAfter;
  entropy_before: EntropyBefore;
  hypothesis_set_id: HypothesisSetId;
  hypothesis_set_version: HypothesisSetVersion;
  posterior?: Posterior;
  predicted_eig: PredictedEig;
  prior?: Prior;
  question_id: QuestionId;
}
export interface Posterior {
  [k: string]: number;
}
export interface Prior {
  [k: string]: number;
}
export interface Event {
  event_id: EventId;
  payload?: Payload;
  run_id: RunId;
  schema_version?: SchemaVersion;
  sequence: Sequence;
  session_id: SessionId;
  timestamp?: Timestamp;
  type: Type1;
}
export interface Payload {
  [k: string]: unknown;
}
export interface EvidenceItem {
  context?: Context;
  current_interpretation?: CurrentInterpretation;
  id: Id3;
  kind: Kind;
  later_learned?: LaterLearned;
  locator: Locator;
  observed_at_time?: ObservedAtTime;
  source_spans?: SourceSpans;
  source_tier: SourceTier1;
  status?: Status4;
  title?: Title;
  version?: Version;
}
export interface SourceSpan {
  quote: Quote1;
  relation?: Relation1;
  turn_id?: TurnId1;
}
export interface HypothesisSet {
  hypotheses: Hypotheses;
  id: Id5;
  latent_variable: LatentVariable;
  status?: Status5;
  version?: Version1;
}
export interface Hypothesis {
  id: Id4;
  p: P;
  text: Text4;
}
export interface InterruptPayload {
  free_text_allowed?: FreeTextAllowed;
  kind: Kind1;
  learning_check_id?: LearningCheckId;
  options?: Options;
  question_id?: QuestionId1;
  text: Text5;
}
export interface QuestionOption {
  id: Id6;
  label: Label;
}
export interface LearningCheck {
  expected_signals?: ExpectedSignals;
  feedback?: Feedback;
  id: Id7;
  kind: Kind2;
  prompt: Prompt;
  status?: Status6;
  user_answer?: UserAnswer;
}
export interface Message {
  content: Content;
  created_at: CreatedAt;
  id: Id8;
  role: Role;
}
export interface Question {
  hypothesis_set_id?: HypothesisSetId1;
  id: Id9;
  kind?: Kind3;
  options?: Options1;
  text: Text6;
}
export interface TaskFrame {
  depth?: Depth;
  desired_output?: DesiredOutput;
  missing_information?: MissingInformation;
  need_fresh_sources?: NeedFreshSources;
  task_type?: TaskType;
  topic: Topic;
  user_context?: UserContext;
  value_criteria?: ValueCriteria;
}
export interface UserContext {
  [k: string]: unknown;
}
export interface ValueCriterion {
  name: Name;
  weight: Weight;
}
